# Generated by Django 3.2.9 on 2021-11-05 11:07

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created',
                 model_utils.fields.AutoCreatedField(default=django.utils.timezone.now,
                                                     editable=False,
                                                     verbose_name='created')),
                ('modified',
                 model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now,
                                                          editable=False,
                                                          verbose_name='modified')),
                ('finished', models.DateTimeField(blank=True, null=True)),
                ('total_steps', models.PositiveIntegerField()),
                ('completed_steps', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created',
                 model_utils.fields.AutoCreatedField(default=django.utils.timezone.now,
                                                     editable=False,
                                                     verbose_name='created')),
                ('modified',
                 model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now,
                                                          editable=False,
                                                          verbose_name='modified')),
                ('message', models.CharField(max_length=255)),
                ('needs_intervention', models.BooleanField(default=False)),
                ('state', models.IntegerField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LogMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created',
                 model_utils.fields.AutoCreatedField(default=django.utils.timezone.now,
                                                     editable=False,
                                                     verbose_name='created')),
                ('modified',
                 model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now,
                                                          editable=False,
                                                          verbose_name='modified')),
                ('message', models.CharField(max_length=500)),
                ('level',
                 models.IntegerField(choices=[(0, 'debug'), (1, 'info'), (2, 'warning'), (3, 'error')], default=0)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
