version: '3.4'

services:

  redis:
    image: redis
    expose:
      - 6379

  db:
    image: "postgres:13"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: address-tool:dev
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/home/app/web
      - media:/media

  celery:
    image: address-tool:dev
    # command: celery -A core worker --loglevel DEBUG
    command: watchmedo auto-restart --directory=./ --pattern=*.py --recursive -- celery -A core worker --concurrency=6 --loglevel DEBUG
    volumes:
      - .:/home/app/web/
    env_file:
      - .env
    depends_on:
      - db
      - redis

  celery-beat:
    image: address-tool:dev
    command: celery -A core beat --loglevel DEBUG
    volumes:
      - .:/home/app/web/
    env_file:
      - .env
    depends_on:
      - celery

  luxdb:
    image: registry.gitlab.com/sacovo/luxdb:latest
    command: ["--loglevel", "DEBUG", "--host", "0.0.0.0", "--port", "8484"]
    expose:
      - 8484
    volumes:
      - luxdb-data:/data
    env_file:
      - .env

volumes:
  postgres_data:
  media:
  luxdb-data:
